site_name: Blue Teams Academy - Free Training 2021
nav:
    - Home: index.md
    - Module 1 - Incident Response and Security Operations Fundamentals: Incident-Response-and-Security-Operations-Fundamentals.md
    - Module 2 - TOP 20 Open-source tools every Blue Teamer should have: top20.md
    - Module 3 - How to deploy your Elastic Stack (ELK) SIEM: elk.md
    - Module 4 - Getting started using Microsoft Azure Sentinel (Cloud-Native SIEM and SOAR) : azure.md
    - Module 5 - Hands-on Wazuh Host-based Intrusion Detection System (HIDS) Deployment : wazuh.md
    - Module 6 - Threat Intelligence Fundamentals: Threat-intelligence-fundamentals.md
    - Module 7 - How to Install and use The Hive Project in Incident Management : hive.md
    - Module 8 - Incident Response and Threat hunting with OSQuery and Kolide Fleet : kolide.md
    - Module 9 - How to use the MITRE PRE-ATT&CK framework to enhance your reconnaissance assessments: MITRE-PRE.md 
    - Module 10 - How to Perform Open Source Intelligence (OSINT) with SpiderFoot: spiderfoot.md
    - Module 11 - How to perform OSINT with Shodan: shodan.md
    - Module 12 - Using MITRE ATT&CK to defend against Advanced Persistent Threats: MITRE-APT.md
    - Module 13 - Hands-on Malicious Traffic Analysis with Wireshark: wireshark.md
    - Module 14 - Digital Forensics Fundamentals: digital-forensics.md
    - Module 15 - How to Perform Static Malware Analysis with Radare2: radare2.md 
    - Module 16 - How to use Yara rules to detect malware: yara.md 
    - Module 17 - Getting started with IDA Pro: ida.md
    - Module 18 - Getting Started with Reverse Engineering using Ghidra: ghidra.md
    - Module 19 - How to Perform Memory Analysis: memory-analysis.md
    - Module 20 - Red Teaming Attack Simulation with "Atomic Red Team": atomic.md
    - Module 21 - How to build a Machine Learning Intrusion Detection system: ML-IDS.md
    - Module 22 - Azure Sentinel - Process Hollowing (T1055.012) Analysis:  processhollowing.md
    - Module 23 - Azure Sentinel - Send Events with Filebeat and Logstash:  filebeat.md
    - Module 24 - Azure Sentinel - Using Custom Logs and DNSTwist to Monitor Malicious Similar Domains: dnstwist.md
    - Azure Sentinel - Code Samples and projects: code.md

google_analytics:
  - UA-193355220-1
  - auto
  
theme: material
